### ISSUE TITLE
Нахождение дорожных знаков на изображении

### ISSUE THREAD

**Issue by DarkFlink** [OSLL/sirius-cv#25]
## Описание задачи

Наша задача теперь - научиться:

1. Разделять на группы массивы найденных точек. То есть уметь обработать ситуацию, когда на изображении несколько дорожных знаков и для каждого уметь строить bounding бокс.
2. Определять, является найденная группа точек в действительности дорожным знаком. Для этого надо найти несколько таких случаев, когда ваша наработка не работает и находит совсем не знак, а какой-то разбросанный набор и придумать как такие ситуации отбрасывать. Заведите пожалуйста отдельный тестовый скрипт с такими картинками, который эту ситуацию моделирует.

## Результат

1. Тест работоспособности на примере с несколькими знаками
2. Тестовый скрипт, который моделирует ситуацию с неадекватным набором точек и алгоритм, который такие случаи дропает

**Comment by danil31219as** [comment]
Не очень понял задачу, она отличается от предыдущей только дропом неправильных точек?

**Comment by DarkFlink** [comment]
> Не очень понял задачу, она отличается от предыдущей только дропом неправильных точек?

Если 1 часть у вас уже есть, то да

**Comment by qmaster0803** [comment]
@qmaster0803 Bounding boxes resize.
