### ISSUE TITLE
Обработка видео

### ISSUE THREAD

**Issue by DarkFlink** [OSLL/sirius-cv#30]
Теперь необходимо научиться тестировать ваши наработки на видео, чтобы можно было не покадрово смотреть на результат а на видосе. Для этого надо:

1. Написать функцию, которой на вход подается cv-видеопоток и абсолютный путь куда сохранить результирующее видео (видео, где обнаруженные знаки обведены гранями)
2. Написать тестовый скрипт, который будет это проверять на каком-то видео

**Comment by danil31219as** [comment]
Для этого нужно передать картинки всех знаков, чтобы было с чем сравнивать картинку?

**Comment by DarkFlink** [comment]
> Для этого нужно передать картинки всех знаков, чтобы было с чем сравнивать картинку?

Сохраняйте их в поля класса. Можете сделать поле-словарь, где будет ключ -- название знака, значение - картинка
Потом в методе класса их оттуда брать

**Comment by danil31219as** [comment]
Скинете датасет с видосами?

**Comment by DarkFlink** [comment]
Видео можете взять например отсюда: http://cvrr.ucsd.edu/LISA/lisa-traffic-sign-dataset.html (рекомендую его, весит прилично, 8гб, но выбор приличный)
Тут видосы разбиты на фреймы, но качать надо меньше - https://btsd.ethz.ch/shareddata/

**Comment by danil31219as** [comment]
Можете скинуть пару видосов? У меня интернет того

**Comment by light5551** [comment]
В дискорде скинул короткое видео с фреймами + разметка

**Comment by DarkFlink** [comment]
https://github.com/OSLL/sirius-cv/wiki/Road-Signs-Datasets
