### ISSUE TITLE
Тестирование решений по object detection

### ISSUE THREAD

**Issue by DarkFlink** [OSLL/sirius-cv#39]
Необходимо в новом блокноте google colab сделать следующее:

1. Скачать и импортировать в блокнот библиотеку https://github.com/matterport/Mask_RCNN
2. Запустить демо-пример из репозитория: https://github.com/matterport/Mask_RCNN/blob/master/samples/demo.ipynb
3. Проверить что на показанном изображении корректно отображаются объекты

Ссылка на преобученную модель https://github.com/matterport/Mask_RCNN/releases/download/v2.0/mask_rcnn_coco.h5

**Как результат:** записанное видео с экрана того, как запускается пример

**Comment by danil31219as** [comment]
h5py 2.10.0
tensorflow 1.5.0
keras 2.0.8
pycocotools-windows (for windows)
mrcnn 0.1
