### ISSUE TITLE
Поиск решений по задаче object detection

### ISSUE THREAD

**Issue by DarkFlink** [OSLL/sirius-cv#43]
Мы сейчас начнем работать с RCNN, но хотелось бы иметь альтернативу. Для этого нужно:

1) Создать вики-страницу в репозитории
2) Найти в интернете несколько (возьмем для ориентира 5) решений задачи object-detection. Основные критерии:
а) Это гитхаб/битбакет/... репозиторий
б) Показано в ридми, что решение позволяет получая на вход изображение выдавать на выход разметку изображения по классам (см скрин в комментариях)

В итоге на вики странице появляется этот список решений в примерно таком виде:

* Решение 1, ссылка: http://google.com
* Решение 2, ссылка: http://google.com
...

**Comment by DarkFlink** [comment]
![image](https://user-images.githubusercontent.com/31723721/111268873-ec91bb00-863e-11eb-849d-0527eefa5cf1.png)

**Comment by danil31219as** [comment]
Закинул
