### ISSUE TITLE
Нахождение контуров на изображении

### ISSUE THREAD

**Issue by DarkFlink** [OSLL/sirius-cv#6]
Задача такая: есть какое-то изображение, нужно сделать его монохромным и применить на нем OpenCV-шный алгоритм нахождения контуров, в библиотеке называется findContours. Для этого нужно последовательно:
- [x] Создать блокнот в Google Colab
- [x] Скачать к себе на компьютер какое-нибудь изображение, например [отсюда](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.mos.ru%2Fnews%2Fitem%2F32651073%2F&psig=AOvVaw2_Tq6znezN3XL-XPQ28HSB&ust=1601130903563000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJjohMrDhOwCFQAAAAAdAAAAABAE), после чего добавить его в файловую систему (ФС) Google Colab (GC)
- [x] Написать код, который сможет считать изображение из ФС GC и отобразить его в блокноте
- [x] Перед строчкой, выводящей в блокнот изображение дописать код, который переведет его в монохромный формат и найдет на нем контуры. Как это сделать на python можно почитать в официальной документации opencv: https://docs.opencv.org/4.1.2/
- [x] Запушить блокнот в этот репозиторий как показывалось на видео, руководствуясь [памяткой](https://github.com/OSLL/sirius-cv/wiki/%D0%9F%D0%B0%D0%BC%D1%8F%D1%82%D0%BA%D0%B0-%D0%B4%D0%BB%D1%8F-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D0%B2-%D1%80%D0%B5%D0%BF%D0%BE%D0%B7%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D0%B8). В этой памятке - базовые простые правила, как мы будем называть пулл-реквесты и ветки, чтобы не было путаницы и анархии.

По всем вопросам - либо в комменты здесь, либо в дискорд.
Успехов!

**Comment by sibenshtern** [comment]
А отображать изображение в блокноте нужно через matplotlib?

**Comment by sibenshtern** [comment]
Нужно ли выводить контуры на изображении?

**Comment by light5551** [comment]
@sibenshtern  Да
