### ISSUE TITLE
Разметка видео

### ISSUE THREAD

**Issue by light5551** [OSLL/sirius-cv#62]
1. https://drive.google.com/drive/folders/1bh8CdiRoIOKpKMtJGxGdVEQ3Cyv3EWVI?usp=sharing  - видео для разметки 
2. Разметка. Берете свое видео и размечаете при помощи инструмента. Кладите все в папку `assets/duckietown_test_1`
3. После того, как все разметят - скомпоновать в одно целое (в папку assets/duckietown_test_1) - за это отвечает @SaviDan245 . Не забудьте прилинковать пулл-реквест к issue справа в интерфейсе гитхаба.

**Comment by DarkFlink** [comment]
1. Поменяем настройки, Егор (настройки запушить в рабочую ветку)
2. Разметка до ПТ вкл

Даниил Савинов, не работает (приоритет):
1. Мас
2. Вин
